# Generated by Django 2.0 on 2017-12-17 16:26
import os
from django.db import connection, migrations


def execute_sql_file(filename):
    """Execute SQL file"""
    path = os.path.join(os.path.dirname(__file__),
                        '../sql/',
                        os.path.basename(__file__).split('.')[0],
                        filename)
    sql_statement = open(path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: execute_sql_file('up.sql'),
            reverse_code=lambda apps, schema_editor: execute_sql_file('down.sql')
        ),
    ]
